/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
#include "opencv2/opencv.hpp"
/* Header for class com_luoluo_pic_algorithm_StripAlgorithm */

#ifndef _Included_com_luoluo_pic_algorithm_StripAlgorithm
#define _Included_com_luoluo_pic_algorithm_StripAlgorithm
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_luoluo_pic_algorithm_StripAlgorithm
 * Method:    getPoint
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_luoluo_pic_algorithm_StripAlgorithm_getPoint
  (JNIEnv *, jobject, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
